### LOGIN
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "chipie.lechat@gmail.com",
  "password": "P@ssword1234"
}

### ME
GET http://localhost:3000/api/auth/me
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjgsInJvbGUiOiJtZW1iZXIiLCJpYXQiOjE3NjE4MzEwMTgsImV4cCI6MTc2MTg0MTgxOH0.6y4l8fRN7GlqufG-DiDKN9SWc-loF0Uqgj6DE8-O73I

### ME update user
## test en modifiant juste le nom OK
PUT http://localhost:3000/api/auth/me
Content-Type: application/json
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjgsInJvbGUiOiJtZW1iZXIiLCJpYXQiOjE3NjE4MzI5OTMsImV4cCI6MTc2MTg0Mzc5M30.mnBtf5BHuSdbHyADniG18qn8vVxitkpy_zuHO7t0rms

{
  "firstname": "Chipie",
  "lastname": "Le chien",
  "email": "chipie.lechat@gmail.com"
}

### ME update user
## test en modifiant juste le mail par celui d'un autre utilisateur OK on a bien une erreur car le mienne appartient à quelqu'un d'autre
PUT http://localhost:3000/api/auth/me
Content-Type: application/json
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjgsInJvbGUiOiJtZW1iZXIiLCJpYXQiOjE3NjE4MzI5OTMsImV4cCI6MTc2MTg0Mzc5M30.mnBtf5BHuSdbHyADniG18qn8vVxitkpy_zuHO7t0rms

{
  "firstname": "Chipie",
  "lastname": "Le chien",
  "email": "octave.lechat@gmail.com"
}

### ME update user
## test sans cookie
PUT http://localhost:3000/api/auth/me
Content-Type: application/json

{
  "firstname": "Chipie",
  "lastname": "Le chat",
  "email": "chipie.lechat@gmail.com"
}


